import { Roboto_Slab } from 'next/font/google'
import './globals.css'
const inter = Roboto_Slab({ preload: false })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[#f1f1f1]">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
